name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest blog posts
        run: |
          for i in {1..10}; do
            curl -H "Accept: application/rss+xml" -H "User-Agent: Mozilla/5.0" -f http://feeds.feedburner.com/Baeldung && break || sleep 30
          done
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/codestackr, http://feeds.feedburner.com/Baeldung"
